name: CI

on: [push, pull_request]

jobs:
  test:
    env:
      DisableGitVersionTask: true
    strategy:
      matrix:
        include:
          - os: windows-latest
            build_config: Debug
          - os: ubuntu-latest
            build_config: Linux-Debug
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Test
      run: dotnet run --project build/Build.csproj -- --target Test --configuration ${{ matrix.build_config }} --clean
  package:
    env:
      DisableGitVersionTask: true
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Package
      run: dotnet run --project build/Build.csproj -- --target Package
    - uses: actions/upload-artifact@v2
      with:
        name: Textrude.zip
        path: publish/Textrude.zip
