name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore -p:Configuration=Linux-Debug
    - name: Build
      run: dotnet build -p:Configuration=Linux-Debug --no-restore
    - name: Test
      run: dotnet test -p:Configuration=Linux-Debug --no-build
